//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialWPF.File
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public Заказы()
        {
            this.Заказчики = new HashSet<Заказчики>();
        }
    
        public int ID_Заказа { get; set; }
        public int ID_Заготовки { get; set; }
        public double Количество { get; set; }
        public System.DateTime Дата_Заказа { get; set; }
    
        public virtual Заготовки Заготовки { get; set; }
        public virtual ICollection<Заказчики> Заказчики { get; set; }
    }
}
