//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialWPF.File
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заготовки
    {
        public Заготовки()
        {
            this.Заказы = new HashSet<Заказы>();
            this.МатериалыЗаготовок = new HashSet<МатериалыЗаготовок>();
            this.Производство = new HashSet<Производство>();
        }
    
        public int ID_Заготовки { get; set; }
        public string Название { get; set; }
        public byte[] Изображение { get; set; }
    
        public virtual ICollection<Заказы> Заказы { get; set; }
        public virtual ICollection<МатериалыЗаготовок> МатериалыЗаготовок { get; set; }
        public virtual ICollection<Производство> Производство { get; set; }
    }
}
