//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialWPF.File
{
    using System;
    using System.Collections.Generic;
    
    public partial class Производство
    {
        public Производство()
        {
            this.Брак = new HashSet<Брак>();
        }
    
        public int ID_Производства { get; set; }
        public int ID_Заготовки { get; set; }
        public string Статус { get; set; }
        public System.DateTime Дата_Начала { get; set; }
        public Nullable<System.DateTime> Дата_Завершения { get; set; }
    
        public virtual ICollection<Брак> Брак { get; set; }
        public virtual Заготовки Заготовки { get; set; }
    }
}
